# Generated by Django 4.2.1 on 2023-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminroom',
            name='video_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
