# Generated by Django 4.2.1 on 2023-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_adminroom_video_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminroom',
            name='video_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
