# Generated by Django 4.2.1 on 2023-08-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_adminroom_video_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminroom',
            old_name='video_room',
            new_name='admin_username',
        ),
    ]
