# Generated by Django 4.2.1 on 2023-05-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='no_of_active_users',
        ),
    ]
