# Generated by Django 4.2.1 on 2023-05-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_server_no_of_active_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_id',
        ),
    ]
