# Generated by Django 4.2.1 on 2023-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_server_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
