# Generated by Django 4.2.1 on 2023-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('server_id', models.CharField(max_length=50, unique=True)),
                ('member', models.CharField(max_length=100)),
            ],
        ),
    ]
