# Generated by Django 4.2.1 on 2023-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0010_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_id', models.CharField(max_length=50, unique=True)),
                ('member', models.CharField(max_length=100)),
            ],
        ),
    ]
