# Generated by Django 4.2.1 on 2023-05-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
