# Generated by Django 4.2.1 on 2023-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0012_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_name', models.CharField(max_length=100)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('member', models.CharField(max_length=100)),
            ],
        ),
    ]
