# Generated by Django 4.2.1 on 2023-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_server__id_alter_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='_id',
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
