# Generated by Django 4.2.1 on 2023-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_remove_server_user_name_server_members_server_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
