# Generated by Django 4.2.1 on 2023-05-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_id'),
        ('groups', '0020_server__id_alter_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='_id',
            field=models.ForeignKey(db_column='_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
        ),
    ]
