# Generated by Django 4.2.1 on 2023-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_alter_server__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
