# Generated by Django 4.2.1 on 2023-05-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_remove_server_user_server_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='users',
            new_name='user',
        ),
    ]
