# Generated by Django 4.2.1 on 2023-05-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_rename_users_server_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='members',
        ),
    ]
