# Generated by Django 4.2.1 on 2023-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_remove_server_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUsers',
            fields=[
                ('server_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
