# Generated by Django 4.2.1 on 2023-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_alter_server_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverusers',
            name='server_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
