# Generated by Django 4.2.1 on 2023-05-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_id'),
        ('groups', '0028_serverusers_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverusers',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='serverusers',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='serverusers',
            name='user_name',
        ),
        migrations.AddField(
            model_name='serverusers',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='serverusers',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_users', to='groups.server'),
        ),
        migrations.AddField(
            model_name='serverusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_servers', to='authentication.users'),
        ),
    ]
