# Generated by Django 4.2.1 on 2023-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_remove_serverusers_server_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusers',
            name='id',
            field=models.CharField(default=0, primary_key=True, serialize=False),
        ),
    ]
