# Generated by Django 4.2.1 on 2023-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_alter_serverusers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverusers',
            name='_id',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='serverusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
