# Generated by Django 4.2.1 on 2023-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_serverusers__id_alter_serverusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusers',
            name='_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
