# Generated by Django 4.2.1 on 2023-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0040_alter_serverusers__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusers',
            name='_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
