# Generated by Django 4.2.1 on 2023-05-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0042_alter_serverusers__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverusers',
            name='_id',
        ),
    ]
