# Generated by Django 4.2.1 on 2023-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0045_remove_serverusers__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverusers',
            name='_id',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
