# Generated by Django 4.2.1 on 2023-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0047_alter_server__id_alter_serverusers__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serverusers',
            name='_id',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
