# Generated by Django 4.2.1 on 2023-05-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0049_alter_server__id_alter_serverusers__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
    ]
