# Generated by Django 4.2.1 on 2023-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0050_alter_server_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusers',
            name='_id',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
