# Generated by Django 4.2.1 on 2023-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0051_alter_serverusers__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Messagetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
