# Generated by Django 4.2.1 on 2023-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_id'),
        ('groups', '0052_message_messagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Messagetype',
        ),
        migrations.AlterField(
            model_name='server',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='servers', to='authentication.users'),
        ),
    ]
