# Generated by Django 4.2.1 on 2023-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_users_id_alter_users_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
